---
title: "Get Help & Give Help!"
output:
  html_document:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---

## Get Help & Give Help!
<br>
<font size = 4.5> When you have a problem in R:

1. Read the documentation: use `?` or, equivalently, `help`.

2. Google it (someone probably already had the same problem and someone else probably told him a way to fix it, probably on [StackOverflow](https://stackoverflow.com/)).

3. Ask it on Stack Overflow (SO) after checking that your question has not already been asked. Some guidelines and resources are available at [SO](https://stackoverflow.com/tags/r/info).

4. Send your question to the noaa coding club, we may not have an answer but we'll try to help you trouble shoot. This email is accessed by volunteers who have offered to help others with coding nmfs.wcr.codingclub 

<br>

Printable [cheat sheets](https://www.rstudio.com/resources/cheatsheets/) have been created for RStudio. They describe a variety of packages and functions within the packages. We've found them to be super helpful as a quick references.  There are several references that have more detail, [An Introduction to R](https://cran.r-project.org/), and [R for Data Science](http://r4ds.had.co.nz/) are two examples.  

<br>

<font size = 6> Continuing coding practice

<font size = 4.5>There are coding clubs to check out where you can practice your coding [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)







