---
title: "Course Agenda and Lessons"
output:
  html_document:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---

## Daily Course Agenda
</br>

All times are in Pacific Time


*Please click on the title to see the session description*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(htmltools)
library(here)
```


```{r}

#Agenda <- data.frame(read_csv("./R Workshop Detailed Schedule.csv", col_names = FALSE))
Agenda <- data.frame(read_csv(here("R_Workshop_Detailed_Schedule_2022.csv"), col_names = FALSE))
# Agenda <- data.frame(read_csv(here("R Workshop Detailed Schedule.csv"), col_names = FALSE))
names(Agenda)<-Agenda[2,]
Agenda<-Agenda[-c(1:2),]
Agenda$Notes0<-Agenda$Notes
Agenda0 <- Agenda

not0<-c("", "??", NA)
Agenda$Date<-paste0(
  Agenda$`Start Time (PT)`, "-", Agenda$`End Time (PT)`
  )
Agenda$Title<-paste0(Agenda$`Course Segment`,
                     ifelse( ( Agenda$`Course Segment` == Agenda$Topics | 
                                 Agenda$`Course Segment` %in% not0 | 
                                 Agenda$Topics %in% not0 ), "", " - "), 
                     ifelse( ( Agenda$`Course Segment` == Agenda$Topics | 
                                 Agenda$Topics %in% not0 ), "", Agenda$Topics) )

Agenda$Authors<-paste0(ifelse(Agenda$Presenter %in% not0, "", paste0("Presenter: ", Agenda$Presenter)), #Presenter
                       ifelse((Agenda$`Chat/Q&A` %in% not0), "", "; "), # ; 
                       ifelse((Agenda$Presenter %in% not0), "", " "), # Space
                       #ifelse(Agenda$Host %in% not0, "", paste0("Host: ", Agenda$Host)), # Host
                       ifelse((Agenda$`Chat/Q&A` %in% not0), "", "; "), # ; 
                       ifelse(Agenda$`Chat/Q&A` %in% not0, "", paste0("Help: ", Agenda$`Chat/Q&A`)) ) # Help

#Agenda$Notes[is.na(Agenda$Notes)]<-""

#Agenda$NotesB[is.na(Agenda$NotesB)]<- ""


Agenda$Notes<-paste0('tags$li(
                      tags$p("Fun-ness: ', Agenda$`Funness`, '"),
                      tags$a(href="', Agenda$Jamboard, '", "Jamboard"),
                      tags$p(""),',
                     ifelse(is.na(Agenda$TutorialA), "",
                            paste0('
                            tags$a(href="', Agenda$TutorialA, '", "Tutorial A"),')),
                      'tags$p(""),',
                      ifelse(is.na(Agenda$TutorialB), "",
                             paste0('
                             tags$a(href="', Agenda$TutorialB, '", "Tutorial B"),')),
                      'tags$p(""),',
                     ifelse(is.na(Agenda$WebLinkA), "",
                            paste0('
                            tags$a(href="', Agenda$WebLinkA, '", "Web Link A"),')),
                      'tags$p(""),',
                     ifelse(is.na(Agenda$WebLinkB), "",
                            paste0('
                            tags$a(href="', Agenda$WebLinkB, '", "Web Link B")')),')'
                     )
                     
                     
   
#Agenda$Notes<-unlist(aa)
#Agenda$NotesB<-unlist(BB)
Agenda<-Agenda[,c("Date","Notes","Title","Authors","Funness", "TutorialA", "TutorialB", "WebLinkA", "WebLinkB", "Jamboard")]
program<-as_tibble(Agenda) #%>%,

days<-unique(Agenda0$Date)

```

```{css}
.schedule {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
}

.limit {
  width: 100%;
  padding: 5px 0 5px 0;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.workshops-button {
  padding: 0.75em 1.25em;
  background-color: #cccccc;
  opacity: 0.9;
  width: auto;
  color: black;
  text-align: center;
  overflow: auto;
}

.left-date {
  width: 20%;
  float: left;
  text-align: left;
}

.center-title {
  width: 60%;
  float: left;
  text-align: left;
  font-size: 120%;
}

.right-authors {
  width: 20%;
  float: right;
  text-align: right;
}

.workshops {
  margin: 1em 1em 0 0;
}

.active {
  background-color: #333333;
  color: whitesmoke;
}

```

```{js}
function main() {
  $('.schedule').hide();
  $('.schedule').fadeIn(2000);
  $('.workshops').hide();
  $('.workshops-button').on('click', function() {
    $(this).next().slideToggle(400);
    $(this).toggleClass('active');
  });
}
 
$(document).ready(main);
```

```{r}
counter0<-1
```

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])))),
     # tags$ul(class = "workshops",
      #        (eval(parse(text=event[["NotesA"]])) ))
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)


```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
     #         # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
             (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>

## `r days[counter0]`

```{r}
program1<-program[grepl(pattern = days[counter0], x = Agenda0$Date), ]

div(
  class = "schedule",
  apply(program1, 1, function(event) {
    div(
      class = "limit",
      div(class = "workshops-button", 
          div(class = "left-date", 
              event[['Date']]),
          div(class = "center-title", 
              # tags$i(event[['Title']])),
              tags$b(event[['Title']])),
          div(class = "right-authors",
              event[['Authors']])),
      tags$ul(class = "workshops",
              (eval(parse(text=event[["Notes"]])) ) )
              # event[["Notes"]])
    )
  })
)

counter0 <- (1 + counter0)

```

<br>



